name: record_workspace
description: Audio recorder from microphone to a given file path with multiple codecs, bit rate and sampling rate options.
version: 5.0.0
homepage: https://github.com/llfbandit/record/tree/master/record
environment:
  sdk: ">=2.17.0 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  melos: ^3.1.1